### ISSUE TITLE
[Testing] Provide unit and/or integration tests for network bundles

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#1547]
Provide unit and/or integration tests for the following packages with subpackages:
* org.eclipse.kura.core.net.*
* org.eclipse.kura.net.admin.*

Implies some of the changes by #1405.

**Comment by cdealti** [comment]
@dwoodard1 @MMaiero @pierantoniomerlino @nicolatimeus @ibinshtok @darionct

@markoer accordingly to the Zenhub book (free pdf available online), if this is an user story (completed in a single sprint) we should use a checkbox list of sub-tasks like this:

- [ ] Provide WifiMonitorServiceImpl unit tests #1548
- [ ] Provide additional tests for ModemMonitorServiceImpl #1550
- [ ] Provide EthernetMonitorServiceImpl unit tests #1554
- [ ] [Testing] Provide DnsMonitorServiceImpl unit tests #1563
- [ ] [Testing] Add additional NetworkAdminServiceImpl tests #1569

Otherwise (multiple sprints) it should be an Epic.

As an user story, when it is moved to the To Do pipeline (aka Sprint Backlog), the estimate should be removed as now we have estimates on sub-tasks (also in the To Do pipeline).

If you prefer to use Epics only as aggregators I'm fine

**Comment by markoer** [comment]
I suppose an Epic would work best, here.

**Comment by MMaiero** [comment]
@markoer Could you please update this issue? Just to know what is the current status. Thanks

**Comment by markoer** [comment]
Currently this is on hold. If/when networking will be refactored further, some additional tests will be necessary. If you feel we should close this issue and then open another one, that's fine by me.

**Comment by MMaiero** [comment]
I'll prefer closing this and open new issues that maybe we can keep on hold.
