### ISSUE TITLE
Wires: Multi-port components and graph execution model

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#1811]
## Current Status
As of Kura 5.1.0 an Wires graph is constituted by nodes (providing the `WireComponent` service interface) and edges (instances of `WireConfiguration`).

A node can be a pure emitter (does not accept incoming edges), a pure receiver or both.

Loops are currently detected and prevented as they might (and will) lead to infinite recursion. 

An emitter can we wired to an arbitrary number of receivers and a receiver can be wired to an arbitrary number of emitters  There is no notion of "port".

The order of execution of the nodes is only partially defined [1]. If the emitter E is wired to the receiver R, R will receive the `WireEnvelope` emitted by E on E's stack. If another receiver R2 is wired to E, it might receive the `WireEnvelope` emitted by E before or after R.

The processing of the received `WireEnvelope` is up to the component. It can be synchronous with the reception or asynchronous if the receiver schedules the processing in a thread.

Almost all WireComponets provided by Kura do the processing synchronously, thus blocking the emitter’s thread.

## The Need of Multi-port Nodes
Applications of multi-port nodes are:
1. Conditional node. The incoming envelope is re-emitted towards one of two downstream receivers based on a condition.
2. Summing node. Sum the "outputs" of upstream emitters.
3. Feedback. The "output" of a node M is computed based on the output of another node N which is reachable from N. In other words there's a loop containing M and N.

It's clear that some of these behaviors can be implemented ad-hoc with the existing implementation.
For example the conditional can be implemented by two sibling nodes evaluating `condition` and `!condition` but we feel more natural the idea of a single node with a `true` and `false` output ports.

An ad-hoc implementation of the summing node is more complex:
* Get it's fan-in (the current number of parent emitters) and allocate an input slot for each emitter
* Store an incoming envelope in the emitter's slot
* When a new envelope is received, sum the values in the slots. Note that envelopes can be received at any time and that initially the slots are empty

Also in this case, it seems more natural to think in terms of input ports.
The node could receive all its inputs in one shot and the bookkeeping described above would be implemented by the wires framework.

## The Need of a Wire Graph Execution Model
For this discussion it is useful to classify nodes as "active" or "passive".
An active node defers the processing of the incoming envelope to an internal thread.
A passive node does the processing on the same stack of the node that emitted the envelope.

The current execution model is trivial.
Starting from a root node, an emitter node calls one of its receiver nodes thus leading to a depth-first execution of the graph.
The call stack of the root node increases up to an active node.
The active node starts a concurrent execution.
The order of execution of sibling nodes is not defined.

The current depth-first execution does not require an execution engine.
It uses the Java call stack and can cause infinite recursion if there are loops.

The simplest way to cope with loops, enabling feedback, is to detect them at runtime inspecting the Java call stack.
Upon receiving an envelope and storing it in a port slot, the wires framework checks the Java call stack and returns if the current frame is in the call stack.
The next execution of the node will use the stored value.

## Conclusions
The changes described above represent a simple extension to the current model and do not add further restrictions.
Likely these changes are backward compatible with existing WireComponent implementations which are treated as having a single input and output ports.
The current execution model and its proposed extension does not follow any work flow model described in the literature.
Popular models like Petri nets or UML Activity Diagrams can maybe supported replacing the wire provider and specializing the nodes.
The opportunity of such implementations is not clear yet.

[1] https://github.com/eclipse/kura/wiki/Kura-Wires-threading-model-proposal

**Comment by MMaiero** [comment]
Following an initial proposal for the multi-port support:

- [ ] Define a Port interface that will be handled by the wireSupporter. The Port(s) will be requested by the application and when the application that wants to emit invokes the emit method of the desired Port(s).

- [ ] The Port implementation contains the list of Wires that are attached

- [ ] Deprecate the old wireSupport APIs as not needed for new components

- [x] Define a WireComponentDefinition POJO that contains:
    - [x] The factory PID
    - [x] The min/max number of input/output ports
    - [x] The default number of input/output ports
    - [x] The default port names
    - [x] The component OCD
    - [ ] isEmitter/isReceiver support methods

- [ ] Define a WireComponentDefinition Service that will have methods to retrieve the WireComponentDefinition(s) (Still needed the new configuration service APIs?)

- [ ] Every new Wire will contain, as an additional property, the int(s) that represent the emitter/receiver port numbers

- [ ] The WireComponentTracker will create a WireSupport for each component tracked and inject the created instance to the corresponding components. For backward compatibility, the tracker will also implement WireSupport and provide the newWireSupport method that behaves as usual, is deprecated and provides support only for single input/output ports.  

Furthermore, every WireComponent that wants to leverage the new Multi port support must specify a set of properties in the component definition that would be:

- input.cardinality.minimum
- input.cardinality.maximum
- input.cardinality.default
- output.cardinality.minimum
- output.cardinality.maximum
- output.cardinality.default

with the following optional properties useful to specify port names:

- input.names
- output.names

Those properties are then used by the Kura Wires related services to identify the emitters, receivers or both and to instantiate properly the different components.

**Comment by MMaiero** [comment]
Closing as multipart support is now part of the codebase
