### ISSUE TITLE
Publish Kura artifacts to Maven Central

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#582]
I think it would be beneficial for Kura to publish artifacts (at least API artifacts) to Maven Central.

Making those artifacts available on Maven Central will make it easier for developers to consume them, implementing their solutions based on Kura.

**Comment by cdealti** [comment]
@ctron this will be introduced by Kura 3.0.0, correct?

**Comment by ctron** [comment]
I really hope so!

**Comment by cdealti** [comment]
@ctron for Zenhub I should set an estimate for this. The estimate is the number of hours it will take.

**Comment by ctron** [comment]
I would say that is implemented. There is one PR pending #1200. But that should be it.

**Comment by ctron** [comment]
So aside from testing and merging this PR no additional time is needed. Unless we need to fix something.

**Comment by cdealti** [comment]
I haven't tested this and I do not know hot to deploy to Maven Central. However this is a release engineering step.

**Comment by cdealti** [comment]
@ctron following-up the meeting in London, is the one below a good approximation to deploy to Maven Central from the p2 repo?

- [ ] Create Kura project on OSSRH #1535
- [ ] File bug at bugs.eclipse.org to be able to deploy to OSSRH from HIPP #1536
- [ ] Test deploy snapshot artifacts from #1200 to https://oss.sonatype.org/content/repositories/snapshots #1537
- [ ] Expand the scope of #1200 defining the Kura features we need, like core, linux, emulator,  driver, asset, wires etc #1538
- [ ] Implement all the Kura features to publish on Maven Central. At this point we should have a Kura p2 repo (without the Kura target platform) that can be converted to maven artifacts that can be deployed on Maven Central #1539
- [ ] Add **nexus-staging-maven-plugin** and test deploy to https://oss.sonatype.org/service/local/staging/deploy/maven2 #1540
